name: entropy
on:
  workflow_dispatch:

jobs:
  cadvisor:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    steps:
      - name: Run stress-ng test
        run: docker run --rm ghcr.io/colinianking/stress-ng --cpu 0.5 --vm-bytes 256M --timeout 3h --label job=${{ github.job }} --label workflow=${{ github.workflow }}
