name: Entropy
on:
  workflow_dispatch:

jobs:
  ephemeral-runner:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: self-hosted
    steps:
    - run: echo "This job uses runner scale set runners!"
